=== cajias2/traffic-simulator/trunk/v2.0/MatLab/src/xml/TrafficSimultion.xsd
<?sim.xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="simulation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="streets" minOccurs='0' maxOccurs='unbounded' />
				<xs:element ref="trayectory" minOccurs='0' maxOccurs='unbounded' />
				<xs:element ref="trafficLights" minOccurs='0' maxOccurs='unbounded' />
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="optional"
				default="Simulation" />			
			<xs:attribute name="maxCars" type="xs:decimal" use="required" />
			<xs:attribute name="simDuration" type="xs:decimal" use="required" />
		</xs:complexType>
	</xs:element>

	<!-- 
		Streets
	 -->
	<xs:element name="streets">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="street" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="street">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="point" minOccurs="2" maxOccurs="unbounded"/>
			</xs:sequence>		
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="orientation" type="orType" use="required" />
			<xs:attribute name="dir" type="dirType" use="required"/>			
		</xs:complexType>
	</xs:element>

	<xs:element name="point">
		<xs:complexType>
			<xs:attribute name="x" type="xs:double" use="required"/>
			<xs:attribute name="y" type="xs:double" use="required"/>
		</xs:complexType>
	</xs:element>	
		 
	<!-- 
		Traffic Lights
	 -->		 
	<xs:element name="trafficLights">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tl" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>



	<xs:element name="tl">
		<xs:complexType>	
			<xs:attribute name="from" type="xs:string" use="required" />
			<xs:attribute name="to" type="xs:string" use="required" />		
			<xs:attribute name="duration" type="xs:integer"" use="required" default="0"/>
			<xs:attribute name="split" type="xs:integer" use="required" default="0"/>
			<xs:attribute name="class" type="xs:string" use="optional"/>		
		</xs:complexType>
	</xs:element>	

	<!--
		Trayectory 
	 -->
	 	<xs:element name="trayectory">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="origin" minOccurs="1" maxOccurs="1" />
				<xs:element ref="destination" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>



	<xs:element name="origin">
		<xs:complexType>	
			<xs:sequence>
				<xs:element ref="streetNode" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="intersection" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>				
		</xs:complexType>
	</xs:element>	
	
	<xs:element name="destination">
		<xs:complexType>	
			<xs:sequence>
				<xs:element ref="streetNode" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="intersection" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>				
		</xs:complexType>
	</xs:element>		
	
	<xs:element name="streetNode">
		<xs:complexType>	
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="percent" type="xs:decimal" use="required" />		
		</xs:complexType>
	</xs:element>		

	<xs:element name="intersection">
		<xs:complexType>	
			<xs:attribute name="from" type="xs:string" use="required" />
			<xs:attribute name="to" type="xs:string" use="required" />			
			<xs:attribute name="percent" type="xs:decimal" use="required" />		
		</xs:complexType>
	</xs:element>		
	
	<!--
		Other Types 
	 -->

	
	<xs:simpleType name="orType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NS"/>
			<xs:enumeration value="EW"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="dirType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="1way"/>
			<xs:enumeration value="2way"/>
		</xs:restriction>
	</xs:simpleType>
	



</xs:schema>

=== cajias2/traffic-simulator/trunk/src/app/xml/traffic/sampleSim.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation maxCars="100" simDuration="1000" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TrafficSimultion.xsd">

    <streets>
        <street name="a" orientation="EW" dir="2way">
        	<point x="10" y="10"/>
        	<point x="600" y="10"/>
        </street>
        <street name="b" orientation="EW" dir="2way">
        	<point x="10" y="20"/>
        	<point x="600" y="20"/>
        </street>
        <street name="c" orientation="EW" dir="2way">
        	<point x="10" y="30"/>
        	<point x="600" y="30"/>
        </street>
        <street name="d" orientation="EW" dir="2way">
        	<point x="10" y="40"/>
        	<point x="600" y="40"/>
        </street>        

        <street name="e" orientation="EW" dir="2way">
        	<point x="10" y="50"/>
        	<point x="600" y="50"/>
        </street>
        <street name="f" orientation="EW" dir="2way">
        	<point x="10" y="60"/>
        	<point x="600" y="60"/>
        </street>
        <street name="g" orientation="EW" dir="2way">
        	<point x="10" y="70"/>
        	<point x="600" y="70"/>
        </street>
        <street name="h" orientation="EW" dir="2way">
        	<point x="10" y="80"/>
        	<point x="600" y="80"/>
        </street>        
        

        <street name="1" orientation="NS" dir="2way">
        	<point x="15" y="5"/>
        	<point x="10" y="600"/>
        </street>
        <street name="2" orientation="NS" dir="2way">
        	<point x="20" y="5"/>
        	<point x="20" y="600"/>
        </street>
        <street name="3" orientation="NS" dir="2way">
        	<point x="30" y="5"/>
        	<point x="30" y="600"/>
        </street>
        <street name="4" orientation="NS" dir="2way">
        	<point x="40" y="5"/>
        	<point x="40" y="600"/>
        </street>                    

        <street name="5" orientation="NS" dir="2way">
        	<point x="50" y="5"/>
        	<point x="50" y="600"/>
        </street>
        <street name="6" orientation="NS" dir="2way">
        	<point x="60" y="5"/>
        	<point x="60" y="600"/>
        </street>
        <street name="7" orientation="NS" dir="2way">
        	<point x="70" y="5"/>
        	<point x="70" y="600"/>
        </street>
        <street name="8" orientation="NS" dir="2way">
        	<point x="80" y="5"/>
        	<point x="80" y="600"/>
        </street>                             
                 
    </streets>

	<trayectory>
		<origin>
			<streetNode name="a" percent="20" />
			<streetNode name="b" percent="20" />
			<streetNode name="c" percent="20" />
			<streetNode name="c" percent="40" />
		</origin>
		<destination>
			<streetNode name="1" percent="25" />
			<streetNode name="2" percent="25" />
			<streetNode name="3" percent="25" />
			<streetNode name="4" percent="25" />
		</destination>
	</trayectory>
	
    <trafficLights>       
        <tl from="a" to="1" duration="100" split="0.5"/>  
        <tl from="a" to="2" duration="100" split="0.5"/>  
        <tl from="a" to="3" duration="100" split="0.5"/>  
        <tl from="a" to="4" duration="100" split="0.5"/>  
        <tl from="a" to="6" duration="100" split="0.5"/>  
        <tl from="a" to="7" duration="100" split="0.5"/>  
        <tl from="a" to="8" duration="100" split="0.5"/>  
        
        <tl from="b" to="1" duration="100" split="0.5"/>  
        <tl from="b" to="2" duration="100" split="0.5"/>  
        <tl from="b" to="3" duration="100" split="0.5"/>  
        <tl from="b" to="4" duration="100" split="0.5"/>  
        <tl from="b" to="6" duration="100" split="0.5"/>  
        <tl from="b" to="7" duration="100" split="0.5"/>  
        <tl from="b" to="8" duration="100" split="0.5"/>  

        <tl from="c" to="1" duration="100" split="0.5"/>  
        <tl from="c" to="2" duration="100" split="0.5"/>  
        <tl from="c" to="3" duration="100" split="0.5"/>  
        <tl from="c" to="4" duration="100" split="0.5"/>  
        <tl from="c" to="6" duration="100" split="0.5"/>  
        <tl from="c" to="7" duration="100" split="0.5"/>  
        <tl from="c" to="8" duration="100" split="0.5"/>  
        
        <tl from="d" to="1" duration="100" split="0.5"/>  
        <tl from="d" to="2" duration="100" split="0.5"/>  
        <tl from="d" to="3" duration="100" split="0.5"/>  
        <tl from="d" to="4" duration="100" split="0.5"/>  
        <tl from="d" to="6" duration="100" split="0.5"/>  
        <tl from="d" to="7" duration="100" split="0.5"/>  
        <tl from="d" to="8" duration="100" split="0.5"/>  

        <tl from="e" to="1" duration="100" split="0.5"/>  
        <tl from="e" to="2" duration="100" split="0.5"/>  
        <tl from="e" to="3" duration="100" split="0.5"/>  
        <tl from="e" to="4" duration="100" split="0.5"/>  
        <tl from="e" to="6" duration="100" split="0.5"/>  
        <tl from="e" to="7" duration="100" split="0.5"/>  
        <tl from="e" to="8" duration="100" split="0.5"/>  

        <tl from="f" to="1" duration="100" split="0.5"/>  
        <tl from="f" to="2" duration="100" split="0.5"/>  
        <tl from="f" to="3" duration="100" split="0.5"/>  
        <tl from="f" to="4" duration="100" split="0.5"/>  
        <tl from="f" to="6" duration="100" split="0.5"/>  
        <tl from="f" to="7" duration="100" split="0.5"/>  
        <tl from="f" to="8" duration="100" split="0.5"/>  

        <tl from="g" to="1" duration="100" split="0.5"/>  
        <tl from="g" to="2" duration="100" split="0.5"/>  
        <tl from="g" to="3" duration="100" split="0.5"/>  
        <tl from="g" to="4" duration="100" split="0.5"/>  
        <tl from="g" to="6" duration="100" split="0.5"/>  
        <tl from="g" to="7" duration="100" split="0.5"/>  
        <tl from="g" to="8" duration="100" split="0.5"/>  

        <tl from="h" to="1" duration="100" split="0.5"/>  
        <tl from="h" to="2" duration="100" split="0.5"/>  
        <tl from="h" to="3" duration="100" split="0.5"/>  
        <tl from="h" to="4" duration="100" split="0.5"/>  
        <tl from="h" to="6" duration="100" split="0.5"/>  
        <tl from="h" to="7" duration="100" split="0.5"/>  
        <tl from="h" to="8" duration="100" split="0.5"/>  
            
          
    </trafficLights>
</simulation>

=== cajias2/traffic-simulator/v3.0/v2.0/MatLab/v2.0/test/simulations/xml/4Streets/4Str_Smart90.xml
<?sim.xml version="1.0" encoding="UTF-8"?>
<simulation maxCars="100" simDuration="10000" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TrafficSimultion.xsd">

    <streets>

        <street name="a" orientation="EW" dir="2way">
        	<point x="10" y="20"/>
        	<point x="600" y="20"/>
        </street>

        <street name="b" orientation="EW" dir="2way">
        	<point x="10" y="40"/>
        	<point x="600" y="40"/>
        </street>        



        <street name="1" orientation="NS" dir="2way">
        	<point x="20" y="5"/>
        	<point x="20" y="600"/>
        </street>

        <street name="2" orientation="NS" dir="2way">
        	<point x="40" y="5"/>
        	<point x="40" y="600"/>
        </street>                                          
                 
    </streets>

	<trayectory>
		<origin>
			<streetNode name="a" percent="90" />
			<streetNode name="1" percent="10" />

		</origin>
		<destination>
			<streetNode name="b" percent="90" />
			<streetNode name="1" percent="10" />

		</destination>
	</trayectory>
	
    <trafficLights>       
        <tl from="a" to="1" duration="100" split="0.5" class="simulations.agents.lights.SmartTFAgent"/>  
        <tl from="a" to="2" duration="100" split="0.5" class="simulations.agents.lights.SmartTFAgent"/>  

        
        <tl from="b" to="1" duration="100" split="0.5" class="simulations.agents.lights.SmartTFAgent"/>  
        <tl from="b" to="2" duration="100" split="0.5" class="simulations.agents.lights.SmartTFAgent"/>  

                      
    </trafficLights>
</simulation>

=== cajias2/traffic-simulator/test/simulations/xml/1CrossSimulation.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation maxCars="100" simDuration="100" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TrafficSimultion.xsd">

    <streets>
        <street name="a" orientation="EW" dir="2way">
        	<point x="10" y="500"/>
        	<point x="990" y="500"/>
        </street>

        <street name="1" orientation="NS" dir="2way">
        	<point x="500" y="10"/>
        	<point x="500" y="990"/>
        </street>
                                          
                 
    </streets>

	<trayectory>
		<origin>
			<streetNode name="a" percent="100" />

		</origin>
		<destination>
			<streetNode name="1" percent="100" />

		</destination>
	</trayectory>
	
    <trafficLights>       
        <tl from="a" to="1" duration="100" split="0.5"/>  
                      
    </trafficLights>
</simulation>
