=== cajias2/traffic-simulator/src/xml/TrafficSimultion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>


	<xs:element name="simulations">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="simulation" minOccurs='1' maxOccurs='unbounded' />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="simulation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="crossings" minOccurs='0' maxOccurs='unbounded' />
				<xs:element ref="connections" minOccurs='0' maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="optional"
				default="Simulation" />
		</xs:complexType>
	</xs:element>

	<xs:element name="crossings">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="crossing" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="crossing">
		<xs:complexType id="crossing">
			<xs:attribute name="name" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="connections">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="connection" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="connection">
		<xs:complexType>
			<xs:attribute name="from" type="xs:string" use="required" />
			<xs:attribute name="to" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>





</xs:schema>

=== cajias2/traffic-simulator/src/xml/sample2.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation maxCars="10" name="Simulation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TrafficSimultion.xsd">

    
    <!--
    	 	    xing2 		xing5	 =	xing8
   		   		  ||		  ||
               @xing3@   =	@xing6@  =  @xing9@	= xing11
  				  ||		  ||			
    xing1	=   xing4      	xing7	 =	xing10
    -->
    <crossings>
 
        <crossing name="xing1" endingOdds="20" startingOdds="20"/>
        <crossing name="xing2" endingOdds="10" startingOdds="20"/>		
        <crossing name="xing8" endingOdds="20"/>		
        <crossing name="xing10" endingOdds="30" startingOdds="40"/>
        <crossing name="xing11" startingOdds="20" endingOdds="20"/>
				
        <crossing name="xing3" hasTrafficLight="true" />
        <crossing name="xing9" hasTrafficLight="true"/>
	    <crossing name="xing6" hasTrafficLight="true"/>
		
        <crossing name="xing4" />
        <crossing name="xing5" />
        <crossing name="xing7" />

    </crossings>
    
    <connections>   
    <!--
    	 	    xing2 		xing5	 =	xing8
   		   		  ||		  ||
               @xing3@   =	@xing6@  =  @xing9@	= xing11
  				  ||		  ||			
    xing1	=   xing4      	xing7	 =	xing10
    -->	    
        <connection from="xing1" to="xing4" orientation="EW" dir="2way" length="10"/>
        <connection from="xing3" to="xing4" orientation="NS" length="10" dir="2way"/>
        <connection from="xing2" to="xing3" orientation="NS" length="10" dir="2way"/>
		        
        <connection from="xing3" to="xing6" orientation="EW" length="10" dir="2way"/>
        <connection from="xing5" to="xing6" orientation="NS" length="10" dir="2way"/>
        <connection from="xing7" to="xing6" orientation="NS" length="10" dir="2way"/>
		
        <connection from="xing6" to="xing9" orientation="EW" length="10" dir="2way"/>
        <connection from="xing7" to="xing10" orientation="EW" length="10" dir="2way"/>
        <connection from="xing5" to="xing8" orientation="EW" length="10" dir="2way"/>
    
	    <connection from="xing9" to="xing11" orientation="EW" length="10" dir="2way"/>
		
		      
    </connections>

</simulation>
