=== cajias2/traffic-simulator/trunk/src/xml/TrafficSimultion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"><!--


	<xs:element name="simulations">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="simulation" minOccurs='1' maxOccurs='unbounded' />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	--><xs:element name="simulation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="crossings" minOccurs='0' maxOccurs='unbounded' />
				<xs:element ref="connections" minOccurs='0' maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="optional"
				default="Simulation" />			
			<xs:attribute name="maxCars" type="xs:decimal" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="crossings">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="crossing" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="crossing">
		<xs:complexType id="crossing">
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="hasTrafficLight" type="xs:boolean" use="optional" default="false"/>
			<xs:attribute name="startingOdds" type="xs:decimal" use="optional" default="0"/>
			<xs:attribute name="endingOdds" type="xs:decimal" use="optional" default="0"/>
			
		</xs:complexType>
	</xs:element>

	<xs:element name="connections">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="connection" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="connection">
		<xs:complexType>
			<xs:attribute name="from" type="xs:string" use="required" />
			<xs:attribute name="to" type="xs:string" use="required" />
			<xs:attribute name="orientation" type="orType" use="required" />
			<xs:attribute name="length" type="xs:double" use="required"/>
			<xs:attribute name="dir" type="dirType" use="required"/>
			<xs:attribute name="lanes" type="xs:decimal" use="required" default="1"/>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="orType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NS"/>
			<xs:enumeration value="EW"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="dirType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="1way"/>
			<xs:enumeration value="2way"/>
		</xs:restriction>
	</xs:simpleType>
	



</xs:schema>

=== cajias2/traffic-simulator/trunk/src/xml/SampleSim.xml
<?xml version="1.0" encoding="UTF-8"?>

<simulation name="Simulation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TrafficSimultion.xsd"
 maxCars="100">
    
    <!--
    	 	 xing2 (Start)
   		   		  ||
    (End)xing3 = xing1 =	xing5 (Start)
  				  ||
    		 xing4 (End)
    -->
    <crossings>
        <crossing name="xing1" hasTrafficLight="true"/>
		
        <crossing name="xing2" startingOdds="50"/>
        <crossing name="xing3" endingOdds="50"/>
        <crossing name="xing4" endingOdds="50"/>
        <crossing name="xing5" startingOdds="50"/>
    </crossings>
    
    <connections>       
        <connection from="xing1" to="xing2" orientation="NS" length="10"/>
        <connection from="xing2" to="xing1" orientation="NS" length="10"/>
        <connection from="xing1" to="xing4" orientation="NS" length="10"/>
        <connection from="xing4" to="xing1" orientation="NS" length="10"/>
        
        <connection from="xing1" to="xing3" orientation="EW" length="10"/>
        <connection from="xing3" to="xing1" orientation="EW" length="10"/>
        <connection from="xing1" to="xing5" orientation="EW" length="10"/>
        <connection from="xing5" to="xing1" orientation="EW" length="10"/>      
    </connections>
</simulation>
